spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3308/ejemplo
    password: '12345'
  application:
    name: ejemplo
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update